"""Inpainting-style diffusion: regenerate a subset of atoms in a structure."""

import time
from typing import Dict, List, Optional, Sequence, Tuple, Union

import numpy as np
import torch
from ase import Atoms
from rich.console import Console

from agedi.data import AtomsGraph

from ._display import _print_inpainting_config
from ._selection import select_atoms


def _as_bool_mask(spec, n_atoms: int) -> np.ndarray:
    """Interpret *spec* as a per-atom bool mask.

    Accepts a bool array of length *n_atoms*, or an integer index sequence,
    and returns a bool mask either way.
    """
    arr = np.asarray(spec)
    if arr.dtype == bool and arr.shape[0] == n_atoms:
        return arr
    mask = np.zeros(n_atoms, dtype=bool)
    mask[np.asarray(spec, dtype=int)] = True
    return mask


def inpaint(
    diffusion: "Agedi",
    atoms: Atoms,
    *,
    indices: Optional[Sequence[int]] = None,
    symbols: Optional[Sequence[str]] = None,
    z_range: Optional[Tuple[float, float]] = None,
    sphere: Optional[Tuple[Sequence[float], float]] = None,
    from_atoms: bool = False,
    fraction: float = 0.25,
    seed: Optional[int] = None,
    freeze: Optional[Sequence[int]] = None,
    n_samples: int = 1,
    t_start: float = 1.0,
    steps: int = 500,
    eps: float = 1e-3,
    batch_size: int = 64,
    n_resample: int = 1,
    jump_length: int = 1,
    cutoff: float = 6.0,
    confinement: Optional[Tuple[float, float]] = None,
    compile: bool = False,
    sampler=None,
    sampler_kwargs=None,
    ff_guidance: Optional["ForcefieldGuidanceConfig"] = None,
    property: Optional[Dict[str, float]] = None,
    progress_bar: bool = False,
    save_trajectory: bool = False,
    save_corrector_frames: bool = False,
    print_timings: bool = False,
    as_atoms: bool = True,
) -> Union[List[AtomsGraph], List[Atoms], List[List[AtomsGraph]], List[List[Atoms]]]:
    """Inpaint a structure: regenerate a chosen subset of its atoms.

    Runs masked reverse diffusion on *atoms*: the selected atoms are noised
    and regenerated by the diffusion model, while every other atom is, at
    each reverse-diffusion step, replaced by a fresh sample from the forward
    process of the input structure — so the whole structure stays at a
    self-consistent noise level throughout, and the non-selected atoms move
    along with the trajectory before converging back exactly onto their
    input positions (and, when a types noiser is active, their input
    species).

    Which atoms are selected is controlled by :func:`~agedi.api.select_atoms`
    (*indices*, *symbols*, *z_range*, *sphere*, *from_atoms* combine by
    union; with none given, a random *fraction* of the non-fixed atoms is
    selected).

    Parameters
    ----------
    diffusion:
        A trained :class:`~agedi.Agedi` model.
    atoms:
        The input structure.
    indices:
        Explicit atom indices to regenerate.
    symbols:
        Regenerate every atom whose chemical symbol is in this list.
    z_range:
        ``(z_min, z_max)``: regenerate atoms whose Cartesian z-coordinate
        falls in this range.
    sphere:
        ``(center, radius)``: regenerate atoms within *radius* of *center*.
    from_atoms:
        Read the selection off ``atoms`` itself (``atoms.arrays["inpaint_mask"]``
        when present, otherwise every atom not held by a ``FixAtoms`` constraint).
    fraction:
        Fraction of the non-fixed atoms selected at random when no other
        selection criterion is given. Defaults to ``0.25``.
    seed:
        Seed for the random-fraction fallback selection.
    freeze:
        Atom indices, or a bool mask, to hard-freeze: these never move and
        are excluded from the forward-marginal replacement applied to the
        rest of the known atoms. Must not overlap the inpainted selection.
        Defaults to ``None`` (nothing frozen beyond the model's own ``FixAtoms``
        handling, if any).
    n_samples:
        Number of independent inpainted structures to generate.
    t_start:
        Starting diffusion time in ``(0, 1]``. ``1.0`` (default) fully
        re-noises the selected atoms (de-novo generation of that region).
        Lower values give a local rattle-and-relax refinement instead.
    steps:
        Number of reverse-diffusion steps.
    eps:
        Minimum time value (end of trajectory).
    batch_size:
        Maximum number of structures sampled in one batch.
    n_resample:
        Number of RePaint-style resampling passes per reverse step. ``1``
        (default) disables resampling.
    jump_length:
        Sub-steps per resampling pass before jumping back. Only meaningful
        when ``n_resample`` > 1.
    cutoff:
        Cutoff radius used when converting ``atoms`` to a graph.
    confinement:
        Optional ``(z_min, z_max)`` confinement bounds.
    compile:
        Not supported for inpainting (the compiled reverse step bypasses
        samplers entirely). Must be ``False``; kept for symmetry with
        :func:`~agedi.api.sampling.sample` and to surface a clear error.
    sampler:
        The *inner* reverse-diffusion algorithm, e.g. ``"em"``, ``"pc"``,
        ``"heun"``. Defaults to Euler-Maruyama.
    sampler_kwargs:
        Extra keyword arguments forwarded to the inner sampler.
    ff_guidance:
        Force-field guidance configuration (requires a model trained with
        ``force_field=True``). Applies only to the selected/regenerated
        atoms — known atoms are left exactly on the forward-marginal /
        reference trajectory the rest of inpainting relies on, regardless of
        guidance strength. Also works with ``sampler="ffpc"``, which blends
        force-field guidance into its own corrector phase.
    property:
        Conditioning property values, e.g. ``{"energy": -3.5}``.
    progress_bar:
        Show a tqdm progress bar.
    save_trajectory:
        When ``True``, return one trajectory per structure instead of a flat
        list of final structures.
    save_corrector_frames:
        Also record every corrector / resampling sub-step. Requires
        ``save_trajectory``.
    print_timings:
        Print a per-stage timing breakdown after sampling.
    as_atoms:
        Convert results to ASE :class:`~ase.Atoms` (default). When ``False``,
        returns :class:`~agedi.data.AtomsGraph` objects instead.

    Returns
    -------
    list
        Inpainted structures (or trajectories, when ``save_trajectory=True``),
        as :class:`~ase.Atoms` or :class:`~agedi.data.AtomsGraph`.

    """
    from agedi.diffusion import ForcefieldGuidanceConfig

    mask = select_atoms(
        atoms,
        indices=indices,
        symbols=symbols,
        z_range=z_range,
        sphere=sphere,
        from_atoms=from_atoms,
        fraction=fraction,
        seed=seed,
    )

    freeze_mask = None
    if freeze is not None:
        freeze_mask = _as_bool_mask(freeze, len(atoms))

    structure = AtomsGraph.from_atoms(
        atoms, cutoff=cutoff, initialize_mask=False, confinement=confinement
    )

    _ff = ff_guidance if ff_guidance is not None else ForcefieldGuidanceConfig()

    if sampler is not None:
        _sampler = sampler if isinstance(sampler, str) else type(sampler).__name__
    else:
        _sampler = None

    _print_inpainting_config(
        n_samples=n_samples,
        n_selected=int(mask.sum()),
        n_atoms=len(atoms),
        steps=steps,
        eps=eps,
        t_start=t_start,
        batch_size=batch_size,
        n_resample=n_resample,
        jump_length=jump_length,
        n_frozen=int(freeze_mask.sum()) if freeze_mask is not None else 0,
        property=property,
        force_field_guidance=_ff.guidance,
        sampler=_sampler,
    )

    _start = time.monotonic()

    diffusion.eval()
    with torch.no_grad():
        sampled = diffusion.inpaint(
            structure,
            mask,
            N=n_samples,
            batch_size=batch_size,
            steps=steps,
            eps=eps,
            t_start=t_start,
            freeze=freeze_mask,
            n_resample=n_resample,
            jump_length=jump_length,
            compile=compile,
            ff_guidance=_ff,
            property=property,
            progress_bar=progress_bar,
            save_trajectory=save_trajectory,
            save_corrector_frames=save_corrector_frames,
            print_timings=print_timings,
            sampler=sampler,
            sampler_kwargs=sampler_kwargs,
        )

    elapsed = time.monotonic() - _start
    n_generated = len(sampled)
    Console().print(
        f"[green]✓[/green] Inpainted {n_generated} structure(s) in {elapsed:.1f}s"
    )

    if not as_atoms:
        return sampled

    if save_trajectory:
        return [[graph.to_atoms() for graph in trajectory] for trajectory in sampled]
    return [graph.to_atoms() for graph in sampled]
