"""Inpainting-style diffusion: regenerate a subset of atoms in a structure."""

import time
from typing import Dict, List, Optional, Sequence, Tuple, Union

import numpy as np
import torch
from ase import Atoms
from rich.console import Console

from agedi.data import AtomsGraph

from ._display import _print_inpainting_config
from ._selection import select_atoms


def _as_bool_mask(spec, n_atoms: int) -> np.ndarray:
    """Interpret *spec* as a per-atom bool mask.

    Accepts a bool array of length *n_atoms*, or an integer index sequence,
    and returns a bool mask either way.
    """
    arr = np.asarray(spec)
    if arr.dtype == bool and arr.shape[0] == n_atoms:
        return arr
    mask = np.zeros(n_atoms, dtype=bool)
    mask[np.asarray(spec, dtype=int)] = True
    return mask


def inpaint(
    diffusion: "Agedi",
    atoms: Union[Atoms, Sequence[Atoms]],
    *,
    indices: Optional[Sequence[int]] = None,
    symbols: Optional[Sequence[str]] = None,
    z_range: Optional[Tuple[float, float]] = None,
    sphere: Optional[Tuple[Sequence[float], float]] = None,
    from_atoms: bool = False,
    fraction: float = 0.25,
    contiguous: bool = False,
    seed: Optional[int] = None,
    freeze: Optional[Sequence[int]] = None,
    n_samples: int = 1,
    t_start: float = 1.0,
    steps: int = 500,
    eps: float = 1e-3,
    batch_size: int = 64,
    n_resample: int = 1,
    jump_length: int = 1,
    cutoff: float = 6.0,
    confinement: Optional[Tuple[float, float]] = None,
    compile: bool = False,
    sampler=None,
    sampler_kwargs=None,
    ff_guidance: Optional["ForcefieldGuidanceConfig"] = None,
    property: Optional[Dict[str, float]] = None,
    progress_bar: bool = False,
    save_trajectory: bool = False,
    save_corrector_frames: bool = False,
    print_timings: bool = False,
    as_atoms: bool = True,
) -> Union[
    List[AtomsGraph], List[Atoms],
    List[List[AtomsGraph]], List[List[Atoms]],
    List[List[List[AtomsGraph]]], List[List[List[Atoms]]],
]:
    """Inpaint one or more structures: regenerate a chosen subset of their atoms.

    Runs masked reverse diffusion on *atoms*: the selected atoms are noised
    and regenerated by the diffusion model, while every other atom is, at
    each reverse-diffusion step, replaced by a fresh sample from the forward
    process of the input structure — so the whole structure stays at a
    self-consistent noise level throughout, and the non-selected atoms move
    along with the trajectory before converging back exactly onto their
    input positions (and, when a types noiser is active, their input
    species).

    Which atoms are selected is controlled by :func:`~agedi.api.select_atoms`
    (*indices*, *symbols*, *z_range*, *sphere*, *from_atoms* combine by
    union; with none given, a random *fraction* of the non-fixed atoms is
    selected).

    Parameters
    ----------
    diffusion:
        A trained :class:`~agedi.Agedi` model.
    atoms:
        The input structure, or a list of structures to batch together for
        GPU throughput. Structures need not share atom count, composition,
        or cell. *indices* / *symbols* / *z_range* / *sphere* / *from_atoms*
        / *fraction* / *freeze* are each a single spec, re-resolved
        independently against every structure in the list (so ``indices=[0]``
        selects atom 0 in each, ``symbols=["O"]`` every oxygen in each,
        etc.) — not a list of per-structure specs. *n_samples* becomes
        *samples per structure*: with a list of ``M`` structures, the result
        has ``M * n_samples`` entries, grouped as one list of ``n_samples``
        results per input structure, in input order.
    indices:
        Explicit atom indices to regenerate.
    symbols:
        Regenerate every atom whose chemical symbol is in this list.
    z_range:
        ``(z_min, z_max)``: regenerate atoms whose Cartesian z-coordinate
        falls in this range.
    sphere:
        ``(center, radius)``: regenerate atoms within *radius* of *center*.
    from_atoms:
        Read the selection off ``atoms`` itself (``atoms.arrays["inpaint_mask"]``
        when present, otherwise every atom not held by a ``FixAtoms`` constraint).
    fraction:
        Fraction of the non-fixed atoms selected at random when no other
        selection criterion is given. Defaults to ``0.25``.
    contiguous:
        When ``True``, the ``fraction`` fallback selects a spatially-connected
        cluster of neighboring atoms (one random seed atom, then repeatedly
        the closest remaining candidate to the growing cluster) instead of a
        scattered random subset. Has no effect when any other selection
        criterion is given. Defaults to ``False``.
    seed:
        Seed for the random-fraction fallback selection.
    freeze:
        Atom indices, or a bool mask, to hard-freeze: these never move and
        are excluded from the forward-marginal replacement applied to the
        rest of the known atoms. Must not overlap the inpainted selection.
        Defaults to ``None`` (nothing frozen beyond the model's own ``FixAtoms``
        handling, if any).
    n_samples:
        Number of independent inpainted structures to generate *per input
        structure* (see *atoms*).
    t_start:
        Starting diffusion time in ``(0, 1]``. ``1.0`` (default) fully
        re-noises the selected atoms (de-novo generation of that region).
        Lower values give a local rattle-and-relax refinement instead.
    steps:
        Number of reverse-diffusion steps.
    eps:
        Minimum time value (end of trajectory).
    batch_size:
        Maximum number of structures sampled in one batch.
    n_resample:
        Number of RePaint-style resampling passes per reverse step. ``1``
        (default) disables resampling.
    jump_length:
        Sub-steps per resampling pass before jumping back. Only meaningful
        when ``n_resample`` > 1.
    cutoff:
        Cutoff radius used when converting ``atoms`` to a graph.
    confinement:
        Optional ``(z_min, z_max)`` confinement bounds.
    compile:
        Not supported for inpainting (the compiled reverse step bypasses
        samplers entirely). Must be ``False``; kept for symmetry with
        :func:`~agedi.api.sampling.sample` and to surface a clear error.
    sampler:
        The *inner* reverse-diffusion algorithm, e.g. ``"em"``, ``"pc"``,
        ``"heun"``. Defaults to Euler-Maruyama.
    sampler_kwargs:
        Extra keyword arguments forwarded to the inner sampler.
    ff_guidance:
        Force-field guidance configuration (requires a model trained with
        ``force_field=True``). Applies only to the selected/regenerated
        atoms — known atoms are left exactly on the forward-marginal /
        reference trajectory the rest of inpainting relies on, regardless of
        guidance strength. Also works with ``sampler="ffpc"``, which blends
        force-field guidance into its own corrector phase.
    property:
        Conditioning property values, e.g. ``{"energy": -3.5}``.
    progress_bar:
        Show a tqdm progress bar.
    save_trajectory:
        When ``True``, return one trajectory per structure instead of a flat
        list of final structures.
    save_corrector_frames:
        Also record every corrector / resampling sub-step. Requires
        ``save_trajectory``.
    print_timings:
        Print a per-stage timing breakdown after sampling.
    as_atoms:
        Convert results to ASE :class:`~ase.Atoms` (default). When ``False``,
        returns :class:`~agedi.data.AtomsGraph` objects instead.

    Returns
    -------
    list
        For a single input structure: a flat list of ``n_samples`` results
        (or trajectories, when ``save_trajectory=True``), as :class:`~ase.Atoms`
        or :class:`~agedi.data.AtomsGraph`. For a list of ``M`` input
        structures: a list of ``M`` lists, each holding that structure's
        ``n_samples`` results, in input order.

    """
    from agedi.diffusion import ForcefieldGuidanceConfig

    is_multi = isinstance(atoms, (list, tuple))
    atoms_list = list(atoms) if is_multi else [atoms]

    masks = [
        select_atoms(
            a,
            indices=indices,
            symbols=symbols,
            z_range=z_range,
            sphere=sphere,
            from_atoms=from_atoms,
            fraction=fraction,
            contiguous=contiguous,
            seed=seed,
        )
        for a in atoms_list
    ]
    freeze_masks = [
        _as_bool_mask(freeze, len(a)) if freeze is not None else None
        for a in atoms_list
    ]
    structures = [
        AtomsGraph.from_atoms(a, cutoff=cutoff, initialize_mask=False, confinement=confinement)
        for a in atoms_list
    ]

    _ff = ff_guidance if ff_guidance is not None else ForcefieldGuidanceConfig()

    if sampler is not None:
        _sampler = sampler if isinstance(sampler, str) else type(sampler).__name__
    else:
        _sampler = None

    _print_inpainting_config(
        n_samples=n_samples,
        n_selected=sum(int(m.sum()) for m in masks),
        n_atoms=sum(len(a) for a in atoms_list),
        steps=steps,
        eps=eps,
        t_start=t_start,
        batch_size=batch_size,
        n_resample=n_resample,
        jump_length=jump_length,
        n_frozen=sum(int(fm.sum()) for fm in freeze_masks if fm is not None),
        property=property,
        force_field_guidance=_ff.guidance,
        sampler=_sampler,
        n_structures=len(atoms_list),
    )

    _start = time.monotonic()

    diffusion.eval()
    with torch.no_grad():
        sampled = diffusion.inpaint(
            structures if is_multi else structures[0],
            masks if is_multi else masks[0],
            N=n_samples,
            batch_size=batch_size,
            steps=steps,
            eps=eps,
            t_start=t_start,
            freeze=freeze_masks if is_multi else freeze_masks[0],
            n_resample=n_resample,
            jump_length=jump_length,
            compile=compile,
            ff_guidance=_ff,
            property=property,
            progress_bar=progress_bar,
            save_trajectory=save_trajectory,
            save_corrector_frames=save_corrector_frames,
            print_timings=print_timings,
            sampler=sampler,
            sampler_kwargs=sampler_kwargs,
        )

    elapsed = time.monotonic() - _start
    n_generated = len(sampled)
    Console().print(
        f"[green]✓[/green] Inpainted {n_generated} structure(s) in {elapsed:.1f}s"
    )

    def _group(flat: list) -> list:
        """Regroup a flat, structure-major list into one sub-list per input
        structure, each holding that structure's n_samples results."""
        if not is_multi:
            return flat
        return [flat[i * n_samples:(i + 1) * n_samples] for i in range(len(atoms_list))]

    if not as_atoms:
        return _group(sampled)

    if save_trajectory:
        converted = [[graph.to_atoms() for graph in trajectory] for trajectory in sampled]
    else:
        converted = [graph.to_atoms() for graph in sampled]
    return _group(converted)
