"""Inpainting sampler — RePaint-style masked reverse diffusion.

Wraps any other :class:`~agedi.diffusion.samplers.Sampler` so that a chosen
subset of atoms (``batch.inpaint_mask``) is regenerated by the base sampler
while the remaining ("known") atoms are, at every reverse-diffusion step,
replaced by a fresh sample from the forward process ``q(z_t | z_0)`` of the
input structure.  This keeps every atom in the batch at the noise level the
score model expects for the current time, so known and generated atoms stay
mutually consistent, and the known atoms converge exactly onto the input
structure as ``t -> eps``.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, List

import torch

from .base import Sampler
from agedi.diffusion.distributions import ZeroComNormal, ZeroComStandardNormal

if TYPE_CHECKING:
    from agedi.data import AtomsGraph
    from agedi.diffusion.noisers import Noiser


class InpaintingSampler(Sampler):
    """RePaint-style inpainting wrapper around a base reverse-diffusion sampler.

    Parameters
    ----------
    base : Sampler
        The resolved sampler that performs the actual reverse-diffusion
        update for every atom (e.g. an :class:`~agedi.diffusion.samplers.EulerMaruyamaSampler`).
        Its :meth:`~agedi.diffusion.samplers.Sampler.step` is called once per
        micro-step (see *jump_length*).
    noisers : list of Noiser
        The noisers attached to the diffusion model, in forward order. Each
        must implement :meth:`~agedi.diffusion.noisers.Noiser.forward_marginal`
        (and, when *n_resample* > 1, :meth:`~agedi.diffusion.noisers.Noiser.renoise`).
    n_resample : int, optional
        Number of RePaint resampling passes per outer diffusion step.  ``1``
        (default) disables resampling: each outer step runs once, matching
        the base sampler exactly except for known-atom projection.
    jump_length : int, optional
        Number of ``dt / jump_length``-sized micro-steps taken forward within
        each resampling pass before jumping back (via the noisers'
        :meth:`~agedi.diffusion.noisers.Noiser.renoise`) to the start of the
        pass.  ``1`` (default) means each pass is a single full-``dt`` step.
        Only meaningful when *n_resample* > 1.

    Notes
    -----
    Expects the batch to carry, for every noiser key ``k``:

    * ``batch.inpaint_mask`` — bool, ``True`` for atoms to regenerate.
    * ``batch[k + "0"]`` — the clean reference value (``z_0``) for ``k``.

    Both are set up by :meth:`~agedi.diffusion.Diffusion._initialize_inpaint_graph`.
    """

    def __init__(
        self,
        base: Sampler,
        noisers: List["Noiser"],
        n_resample: int = 1,
        jump_length: int = 1,
    ) -> None:
        if n_resample < 1:
            raise ValueError(f"n_resample must be >= 1, got {n_resample}")
        if jump_length < 1:
            raise ValueError(f"jump_length must be >= 1, got {jump_length}")
        # Set before super().__init__() runs: its assignment to
        # ``self.save_corrector_frames`` goes through the property setter
        # below, which forwards to ``self.base``.
        self.base = base
        super().__init__(base.score_fn, noisers)
        self.n_resample = n_resample
        self.jump_length = jump_length

    @property
    def uses_force_field(self) -> bool:  # type: ignore[override]
        """Delegate to the wrapped base sampler."""
        return self.base.uses_force_field

    @property
    def save_corrector_frames(self) -> bool:  # type: ignore[override]
        """Whether sub-step frames are captured; forwarded to the base sampler.

        The base sampler's own :meth:`~agedi.diffusion.samplers.Sampler._capture_frame`
        calls (e.g. Langevin corrector sub-steps) are only active when its own
        ``save_corrector_frames`` is set, so writes here are mirrored onto
        :attr:`base` as well.
        """
        return self._save_corrector_frames

    @save_corrector_frames.setter
    def save_corrector_frames(self, value: bool) -> None:
        self._save_corrector_frames = value
        self.base.save_corrector_frames = value

    def step(
        self,
        batch: "AtomsGraph",
        dt: torch.Tensor,
        last: bool,
    ) -> "AtomsGraph":
        """Perform one outer reverse-diffusion step with known-atom projection.

        For each of *n_resample* passes:

        1. Project known atoms onto ``q(z_t | z_0)`` at the pass's start time.
        2. Run *jump_length* micro-steps of the base sampler, projecting known
           atoms after every micro-step (exactly, on the very last micro-step
           of the very last pass; from the forward marginal otherwise).
        3. If this is not the last pass, jump back: re-noise the *entire*
           batch (known and generated atoms alike) from the pass's end time
           back up to its start time via each noiser's ``renoise``. Known
           atoms are immediately re-projected at the top of the next pass, so
           only the generated atoms' re-noised state actually carries over.
        """
        self._reset_pending()

        t_start = batch.time.clone()
        micro_dt = dt / self.jump_length

        for resample_i in range(self.n_resample):
            is_last_resample = resample_i == self.n_resample - 1

            batch.time = t_start.clone()
            self._project_known(batch, exact=False)

            t = t_start.clone()
            for micro_i in range(self.jump_length):
                is_final_state = is_last_resample and micro_i == self.jump_length - 1
                micro_last = last and is_final_state

                batch = self.base.step(batch, micro_dt, micro_last)
                # Forward any sub-step frames captured inside the base
                # sampler (e.g. PC/FFPC Langevin correctors) into our own
                # pending list, which _sample_batch reads after step() returns.
                if self.base._pending_frames:
                    self._pending_frames.extend(self.base._pending_frames)

                t = (t - micro_dt).clamp(min=0.0)
                batch.time = t.clone()
                self._project_known(batch, exact=micro_last)

                if not is_final_state:
                    self._capture_frame(batch)

            if not is_last_resample:
                self._renoise_all(batch, t_from=t, t_to=t_start)
                batch.time = t_start.clone()
                self._capture_frame(batch)

        return batch

    # ------------------------------------------------------------------
    # Internals
    # ------------------------------------------------------------------

    @staticmethod
    def _expand_like(mask: torch.Tensor, tensor: torch.Tensor) -> torch.Tensor:
        """Broadcast a per-atom bool mask to the trailing shape of *tensor*."""
        if tensor.dim() > mask.dim():
            shape = [mask.shape[0]] + [1] * (tensor.dim() - 1)
            return mask.view(*shape)
        return mask

    def _project_known(self, batch: "AtomsGraph", exact: bool) -> None:
        """Overwrite known (non-inpainted) atoms with the reference process.

        When *exact* is ``False``, known atoms are set to a fresh sample of
        ``q(z_t | z_0)`` at the current ``batch.time``. When *exact* is
        ``True`` (the final micro-step of the final resampling pass), known
        atoms are restored exactly to their reference value ``z_0``.
        """
        known = ~batch.inpaint_mask
        if not known.any():
            batch.wrap_positions()
            self._check_finite(batch, "inpainting known-atom projection")
            batch.update_graph()
            return

        for noiser in self.noisers:
            key = noiser.key
            ref = batch[key + "0"]
            current = batch[key]

            if exact:
                new_val = ref
            else:
                new_val = noiser.forward_marginal(batch, ref)

            mask = self._expand_like(known, current)
            merged = torch.where(mask, new_val, current)
            merged = self._recenter_zero_com(noiser, batch, merged, ref, t=batch.time)

            setattr(batch, key, merged)

        batch.wrap_positions()

        if exact:
            # wrap_positions() can flip an atom sitting exactly at a
            # periodic-cell boundary to the adjacent image -- a jump by a
            # full lattice vector, not a small numerical wobble. Known atoms
            # must be bit-exact on the final step, so force them back to the
            # true (unwrapped) reference now that wrapping is done; setattr
            # here does not itself re-wrap.
            for noiser in self.noisers:
                key = noiser.key
                ref = batch[key + "0"]
                current = batch[key]
                mask = self._expand_like(known, current)
                setattr(batch, key, torch.where(mask, ref, current))

        self._check_finite(batch, "inpainting known-atom projection")
        batch.update_graph()

    def _renoise_all(
        self,
        batch: "AtomsGraph",
        t_from: torch.Tensor,
        t_to: torch.Tensor,
    ) -> None:
        """Re-noise every atom (known and generated) from ``t_from`` to ``t_to``.

        Used for the RePaint "jump back" between resampling passes. Applied
        to the whole batch for simplicity; known atoms are unconditionally
        overwritten again by :meth:`_project_known` immediately afterwards,
        so only its effect on the generated atoms actually persists.
        """
        for noiser in self.noisers:
            key = noiser.key
            current = batch[key]
            new_val = noiser.renoise(batch, current, t_from, t_to)
            setattr(batch, key, new_val)

        batch.wrap_positions()
        self._check_finite(batch, "inpainting resample jump-back")
        batch.update_graph()

    def _recenter_zero_com(
        self,
        noiser: "Noiser",
        batch: "AtomsGraph",
        merged: torch.Tensor,
        ref: torch.Tensor,
        t: torch.Tensor,
    ) -> torch.Tensor:
        """Re-centre a partially-replaced positions tensor for zero-COM noisers.

        :class:`~agedi.diffusion.distributions.ZeroComNormal` /
        :class:`~agedi.diffusion.distributions.ZeroComStandardNormal` project
        the *noise increment* to zero centre-of-mass across *all* atoms of a
        graph. Overwriting only a subset of atoms (the known ones) breaks
        that invariant, since the zero-com correction was computed assuming
        every atom in the graph would receive the new sample. This restores
        it by shifting the merged per-graph centre of mass back to the
        expected running value ``mean(t) * COM(ref)``.

        No-op for any noiser that is not a positions noiser using one of the
        zero-COM distributions (e.g. periodic/cell noisers, which have no
        translational symmetry to preserve).
        """
        distribution = getattr(noiser, "distribution", None)
        sde = getattr(noiser, "sde", None)
        if not isinstance(distribution, (ZeroComNormal, ZeroComStandardNormal)):
            return merged
        if sde is None or merged.dim() != 2:
            return merged

        batch_idx = batch.batch
        n_graphs = int(batch_idx.max().item()) + 1
        count = batch_idx.bincount(minlength=n_graphs).float().view(-1, 1)

        def _per_graph_com(x: torch.Tensor) -> torch.Tensor:
            com = torch.zeros(n_graphs, x.shape[1], dtype=x.dtype, device=x.device)
            com.scatter_add_(0, batch_idx.unsqueeze(1).expand_as(x), x)
            return com / count

        current_com = _per_graph_com(merged)
        ref_com = _per_graph_com(ref)
        # All atoms in a graph share the same time, so this per-graph average
        # of ``mean(t)`` is exact, not an approximation.
        mean_t_graph = _per_graph_com(sde.mean(t))
        target_com = mean_t_graph * ref_com

        shift = (target_com - current_com)[batch_idx]
        return merged + shift
